pyaedt.Edb.edb\_exception
=========================

.. currentmodule:: pyaedt

.. automethod:: Edb.edb_exception